name: geschenkerbauer action
description: Build Arch Linux packages
inputs:
  package:
    description: Package to build
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.package }}
