name: geschenkerbauer action
description: Build Arch Linux packages
inputs:
  packages:
    description: Packages to build (in order)
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.packages }}
