name: autosign govulncheck

on:
  push:
    branches:
      - 'main'
    paths:
      - 'autosign/**'
  workflow_dispatch:

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-package: ./...
           go-version-file: autosign/go.mod
           work-dir: autosign
