name: Update a package from the AUR
description: Update a package from the AUR
inputs:
  pkgbase:
    description: "Package base name"
    required: true
runs:
  using: composite
  steps:
    - name: Change default shell to bash
      shell: bash
      run: |
        sudo ln -sf /bin/bash /bin/sh
    - name: Pull subtree from AUR
      shell: bash
      env:
        pkgbase: ${{ inputs.pkgbase }}
      run: |
        if [ -d "${pkgbase}" ]; then
          git subtree split -q -P "${pkgbase}" --rejoin
          git subtree pull -q -P "${pkgbase}" https://aur.archlinux.org/"${pkgbase}".git master -m "Merge subtree '${pkgbase}'"
        else
          git subtree add -q -P "${pkgbase}" https://aur.archlinux.org/"${pkgbase}".git master
        fi
